### PR TITLE
Issue datacite/sashimi#133 - Add file backup for reports stored in S3.

### PR DESCRIPTION
**Pull request by svogt0511**
## Purpose

Adds backup to reports files in s3 storage.

## Approach

Uses the version, lifecycle, and expiration features of the AWS S3 bucket to keep old versions of modified/deleted files, and to save costs by transitioning them to lower cost storage after given amounts of time.  Expiration is set to delete older versions after 365 days.

#### Open Questions and Pre-Merge TODOs

Only added settings to stage for testing.  Once this has been confirmed to do no harm to what we have, settings can be moved to production, as well.

## Learning

[Should You Back Up an Ultra-Redundant Object Storage Service?](https://www.groupwaretech.com/ultra-redundant-object-storage-service-absolutely/#:~:text=AWS%20themselves%20say%3A%20%E2%80%9CAmazon%20S3,failures%2C%20errors%20and%20threats.%E2%80%9D)
[Managing Your Amazon S3 Storage](https://docs.aws.amazon.com/AmazonS3/latest/userguide/managing-storage.html)
[Terraform Resource: aws_s3_bucket configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)

- [x] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Reviewer, please remember our [guidelines](https://datacite.atlassian.net/wiki/spaces/TEC/pages/1168375809/Pull+Request+Guidelines):

- Be humble in the language and feedback you give, ask don't tell.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing negative.
- Offer suggestions on how to improve code e.g. simplification or expanding clarity.
- Ensure you give reasons for the changes you are proposing.

### CODE REVIEW

**Review by mfenner — COMMENTED** [review]
I would call the bucket "metrics-api-stage" or "metrics-stage" to be consistent.

**Comment by svogt0511** [comment]
@mfenner - Some questions.

I tried changing the name on the resource as you suggested("metrics" => "metrics-api-stage").  The result was this [proposed run](https://app.terraform.io/app/datacite-ng/workspaces/stage-services-metrics-api/runs/run-fkhKASyUTBoy7iiK) which destroys the resource, and I am pretty sure, deletes the bucket.  Of course this is not the desired result.  We just want to change bucket properties.

So then, I put the resource name back to what it was ("metrics") and the [proposed run](https://app.terraform.io/app/datacite-ng/workspaces/stage-services-metrics-api/runs/run-Tqp9Fux7Ytujs467) was an update in place of the resource.  That is what we want.

However, that made me wonder what side effects would be of having a resource of the same name associated with 2 different s3 buckets (a "metrics" resource in stage, and a "metrics" resource in production).  That is what we have now, which may be ok.  So far it seems to be.  So I am thinking that we just leave the resource name as is for now, unless there is a way to change the resource without deleting it.

My other question is that there is a variable named 'librato_token' that is generating a warning. I am just going to add a variable for it to var.tf to take care of the warning.

**Comment by mfenner** [comment]
librato is a service we used to use some time ago. DataDog has replaced it.

Bucket names should be globally unique, so a dns name is a good choice. You might be able to rename manually in the AWS console.

**Comment by svogt0511** [comment]
The bucket names are globally unique.  They are set per environment, for ex, staging is:

`variable "s3_bucket" {
  default = "metrics-api.stage.datacite.org"
}`

As I understand, the resource names need to be consistent so, for example, I tried changing the bucket resource name in main.tf from:

`resource "aws_s3_bucket" "metrics" {`

to:

`resource "aws_s3_bucket" "metrics-api-stage" {`

Perfectly reasonable to want to do that, but not as easy as it looks.  Changing the name causes terraform to want to delete the resource, including the bucket then recreate it.  I assume that would result in an empty bucket.  

In order to rename the resource, I am finding that you have to log in using the terraform cli, find the correct workspace, and run the following command (see [stackoverflow discussion](https://stackoverflow.com/questions/58876535/renaming-s3-bucket-in-terraform-but-not-s3-causes-create-then-destroy)):

`terraform state mv aws_s3_bucket.metrics aws_s3_bucket.metrics-api-stage`

I have been able to login, but am not in the correct organization and so cannot navigate to the stage-services-metrics-api workspace to run the command.

Quite a complicated process for just wanting to change the resource name.  Do you have any suggestions?

Thanks.

**Comment by svogt0511** [comment]
The other changes in this pull request were to turn on versioning and add a life cycle for versioned files for backup.

**Comment by svogt0511** [comment]
I am planning on merging this to master. That will allow me to test this in stage, When I see that nothing bad has happened there, then I will make the same changes for production and merge it to production. @mfenner, if you have any comments, let me know.  Thanks.

**Pull request merged**
