### PR TITLE
Issue 1461 - SALESFORCE LOCKED RECORDS DURING SYNC

### PR DESCRIPTION
**Pull request by svogt0511**
## Purpose

closes: datacite/datacite#1461

## Approach

Use the [Salesforce suggested solution](https://developer.salesforce.com/docs/atlas.en-us.draes.meta/draes/draes_object_relationships_record_level_locking.htm) of adding retry logic to our integration code.  We use axios to integrate our applications with the Salesforce REST API.  Tried axios-retry which seems to work fine in stage.  The real test will be the nightly Salesforce sync.  We should not see any more UNABLE_TO_LOCK_ROW error reports in #ops.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)

- [ ] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Reviewer, please remember our [guidelines](https://datacite.atlassian.net/wiki/spaces/TEC/pages/1168375809/Pull+Request+Guidelines):

- Be humble in the language and feedback you give, ask don't tell.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing negative.
- Offer suggestions on how to improve code e.g. simplification or expanding clarity.
- Ensure you give reasons for the changes you are proposing.

### CODE REVIEW

**Comment by richardhallett** [comment]
I don't think you meant to check in the node_modules

**Comment by svogt0511** [comment]
> I don't think you meant to check in the node_modules

Removed from tracking.

**Comment by svogt0511** [comment]
> I realise now that node_modules was originally commited, not sure why. Maybe for deployment purposes? I'd rather not have it checked in though.

I am not sure why it was committed originally. It seems that it is not needed for deployment purposes.  It is added to the zip file and that is what is used for deployment.  I tested it when I removed node_modules from git tracking.

**Comment by svogt0511** [comment]
> > I realise now that node_modules was originally commited, not sure why. Maybe for deployment purposes? I'd rather not have it checked in though.

Thinking about it, I will put it back because it saves you from having to do a a step in deploying.  You create the zip files using the node_modules directory, package.json and the and the appropriate .js file, so yes it is used in deployment. :-)

**Pull request merged**
