### PR TITLE
S3 bucket for resolution logs

### PR DESCRIPTION
**Pull request by kjgarza**
## Purpose

Adds an S3 bucket for resolution logs

addresses: https://github.com/datacite/datacite/issues/1104

## Approach
Using S3 bucket to store raw logs

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)

- [x] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Reviewer, please remember our [guidelines](https://datacite.atlassian.net/wiki/spaces/TEC/pages/1168375809/Pull+Request+Guidelines):

- Be humble in the language and feedback you give, ask don't tell.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing negative.
- Offer suggestions on how to improve code e.g. simplification or expanding clarity.
- Ensure you give reasons for the changes you are proposing.

### CODE REVIEW

**Review by mfenner — COMMENTED** [review]
Please use terraform 0.12 for all new terraform infrastructure.  Why do you need aws provider in us-east-1?

**Comment by kjgarza** [comment]
not using that seems to be a common pattern in all our S3 configurations. See mastino repo.

**Review by mfenner — COMMENTED** [review]
Please address the comments from the previous review.

**Review by mfenner — APPROVED** [review]
LGTM

**Pull request merged**
